version: "3.8"

services:
  nginx:
    image: anittajose/sprint-board:nginx-latest
    restart: always
    depends_on:
      - client
      - server
    ports:
      - "80:80"

  client:
    image: anittajose/sprint-board:client-latest
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}

  server:
    image: anittajose/sprint-board:server-latest
    environment:
      - PORT=${PORT}
      - DB_CONNECT=${DB_CONNECT}
      - TOKEN_KEY=${TOKEN_KEY}
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      