POST REACT_APP_BACKEND_URL/api/item
Content-Type: application/json

{
  "item": "This is the second todo item"
}

###

GET REACT_APP_BACKEND_URL/api/items
Content-Type: application/json

###

PUT REACT_APP_BACKEND_URL/api/item/6245bfd3eb7b72345090f275
Content-Type: application/json

{
  "item": "This is the second todo item updated!!"
}

###

DELETE  REACT_APP_BACKEND_URL/api/item/6245bad3eb7b72345090f273
Content-Type: application/json
